### ISSUE TITLE
Cut-off of custom background image in PNG format

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#10]
When I converted my custom graphics of my level into PNG format, I was found small bug with background images: instead of normal background drawing I see a cut-off. Same image in GIF format works fine.
(Are you accidentally swapped width and height values while created texture?)
![2015-10-25_23_39_12](https://cloud.githubusercontent.com/assets/6751442/10717726/d4112fda-7b71-11e5-9469-c4cd787d808a.png)

Background Image used for this screen-shot:
![background2-11](https://cloud.githubusercontent.com/assets/6751442/10717673/3dbff45e-7b70-11e5-9c67-3b7b2881e343.png)

**Comment by Bluenaxela** [comment]
Was this with a image size different from the default gif one? If so, I now understand the problem.

Currently the handling of .png images swaps which one will be rendered, but it does not change what rectangle of pixels SMBX will try to draw.

For things like blocks and NPCs, the image file dimensions are not used anyway to decide what rectangle to draw, so this is not an issue.
For level backgrounds (and certain effects I think), SMBX does use the image file dimensions when deciding how to draw, so there is an issue currently.

**Comment by Bluenaxela** [comment]
This issue was fixed in the new graphics loading system.
