### ISSUE TITLE
Crash after gif recorder tested in the editor

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#11]
Just tried on a newly installed Windows 7 install LunaLUA 0.7.2
I found than when I trying to record short gif, it crashes SMBX after 10 sec when I enabled recording of gif, even I stopped it immediately.

**Comment by KevinW1998** [comment]
I know, gifs are memory eater and there is nothing I can do about this bug. Gifs are meant for very short clips, not for whole videos.

**Comment by Wohlstand** [comment]
Are you recoding frames to disk instead of RAM or you recording frames into memory?
I think, is good to record buffer into disk even performance will lag, and then build animated gif when recorder stopped. Hedgewars doing same: records temporary video file and then converts it into video of target format with selected codec

**Comment by KevinW1998** [comment]
I would, if I could.

Neither FreeImage nor WIC allows flushing.

**Comment by Wohlstand** [comment]
You can store image frames as raw data into temp file, and then compress each frame after finishing of record. I.e. Each frame is BMP pixel array which has persistant length. Store pixel array into end if raw binary file each frame via regular file I/O functions. When you doing to generate target gif, just read each frame with same length of pixel array and then record it into gif as frame.
EDIT: Are you mean than to generate target GIF is needed to build entire gif in memory before save?

**Comment by KevinW1998** [comment]
You don't understand: The recorder saves frame in memory (this is not the problem)

But if you finished recording, then freeimage is copying all data in memory and puts the gif together. It is something I cannot change, it is just how FreeImage works.

**Comment by Wohlstand** [comment]
I think would be similar algorithm:

``` Text
start record
1) Open binary file
2) Each loop store raw pixels into file (and count frames!)
stop record
3) close file and reopen for read
4) open target GIF for writing and write header
5) read first frame from raw file (length is same)
6) compress it via GIF algorithm and store as GIF frame
7) repeat 5 and 6 until all frames will be recorded 
```

I think, this way required us to apply our old friend - giflib. It supports animated gifs, but we are never used that thing. Anyway, this way will record unlimitely big GIF with less memory usage
Anyway, even super-short gif showcases would eat much memory in decompressed state (try to save same number of BMP's)

**Comment by Wohlstand** [comment]
I have some solution to prevent crash:

``` C++
void* ptr = new char[image.datasize];//Let's allocate some memory block
if(!ptr) //If block is null - that means - out memory, and we can do our work SAFE:
{
    //Can't make GIF, out of memory
    //Or instead of error, reduce size (crop frames which are not fiting into current memory size!)
} else {
    //Do actual GIF generating through "ptr"
}
```

**Comment by Bluenaxela** [comment]
I'd recommend against only relying on failed allocation for this. There is
code that will run in other threads and may also have failed allocations.
Better to also set a "generally reasonable" length limit.

**Comment by Wohlstand** [comment]
Another idea to optimize memory usage - using a file mapping, I.e. read/write access to the file like you accessing memory. So, instead lf allocating of a huge space, just make a temp file which will be deleted after saving of the target gif.

**Comment by KevinW1998** [comment]
File management is handled by FreeImage and AFAIK, it only can save with full ImageContainer and not partially containers..

**Comment by Wohlstand** [comment]
But I think, what if we are will make own GIF recorder? I.e. let FreeImage compress every frame, but store it to end of file by own writer class

**Comment by Bluenaxela** [comment]
I think we should simply move away from FreeImage for GIF writing. It's not good for this task.

There are plenty of other GIF writing libraries that can allow incremental writing of the file.
~~http://giflib.sourceforge.net/gif_lib.html is a lower level library that requires more manual handling of things like the color mapping, but can write incrementally frame by frame just fine.~~

Or how about we just use this header:
https://github.com/ginsweater/gif-h
Very very simple, has no dependencies except standard C headers, writes incrementally frame by frame, supports frame differencing, doesn't have inflating memory usage with each frame, support optional dithering if we want it... It looks perfect for what we want.

**Comment by Wohlstand** [comment]
Great!, We must to test it!
