### ISSUE TITLE
Freezing of game after loading on interocess test launch on slow machines

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#17]
This is an old issue. When PGE Editor launches a starting a level test on fast machine, everything works fine. But when PGE Editor starts same level test on slow machine (for example, under VirtualBox), SMBX freezing after loading of stuff with just launched playing of music.

**Comment by Bluenaxela** [comment]
A lot of changes to relevant areas have happened since this, and haven't been able to reproduce.

**Comment by Wohlstand** [comment]
This is also "completed", just because I completely reworked the interprocess mechanism at Moondust Editor, and this issue is no longer actual, as the rework work automatically resolved this problem. And so, even the last LunaLua-SMBX and SMBX2 Beta3 works just fine while working under VM.
