### ISSUE TITLE
OpenGL still be enabled while using LunaTester

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#19]
When video card is too old (doesn't suports OpenGL 3+), GDI usually in use. This works in regular game mode, but in case of LunaTester (starting level testing from PGE Editor via pipe in the legacy SMBX Engine) seems OpenGL engine still be enabled and SMBX Engine is freezing or even crashing.

Example of the case has been reported here:
http://www.supermariobrosx.org/forums/viewtopic.php?f=35&t=17021&p=247958

> Basically, when I use the luna-tester, the game stops working.
Here is a screenshot
![sharex_2016-10-28_23-05-28](https://cloud.githubusercontent.com/assets/6751442/20608189/c909efe6-b298-11e6-845f-3efdad78fdb8.png)
And my PC specs if you really need them:
Processor: Intel(R) Core(TM)i5 CPU M520 @2.40GHz 2.40GHz
4.00 GB RAM of which 2.93 GB is usable
Type: 32-bit operating system
GFX card: Standard VGA Graphics adapter

First in the mind was missed video driver. But even driver has been installed, still doesn't working. Anyway, I requested that guy to detect absolute model of video card via Everest utiltiy.

**Comment by Bluenaxela** [comment]
Support for the GDI renderer is removed, so this is no longer relevant. (opengl32sw.dll will be used for a software renderer fallback in the future)
