### ISSUE TITLE
Hard CPU overload when OpenGL is disabled and window is closed into background.

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#20]
When I implemented ability to run LunaTester with disabling OpenGL on SMBX Engine (by appending `--nogl` argument), I found that when I closing it, it heavy overloads CPU and causes a huge lag of PGE Editor and entire PC (VirtualBox machine with a single CPU core).

**Comment by Wohlstand** [comment]
Okay, with having of `LunaTester-exec`, this issue is now isolated and Editor is now in safe.

**Comment by Bluenaxela** [comment]
Stale and no longer applicable.

**Comment by Wohlstand** [comment]
Also just because I reworked the whole Interprocess mechanism at the Moondust Editor side. This issue supposed to be closed quickly after tests and checks. Seems I totally forgot to close this. It must be "completed" rather "not planned".
