### ISSUE TITLE
Implement the simplified and minimalistic lanuncher for Windows XP

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#21]
Since mainstream launcher has switched latest Qt 5.11, it is no more supports Windows XP as last Qt that officially supported Windows XP is 5.6 and last Qt that still work on Windows XP is Qt 5.7.

Simplified launcher will be written in pure C with pure WinAPI and give minimalistic layout that needs to start PGE Editor or LunaLua Engine. To have an ability to pass the list of episodes to launch any of it individually, use PGE File Library in STL mode (use a separated cpp file that will manage C++-only PGE File Library and fill the combo-box with a data). To choose which launcher will be started, add the Windows version detection into SMBX2.exe that laying in the root of SMBX2 repo.

**Comment by LoveBodhi** [comment]
Two launchers?

**Comment by Wohlstand** [comment]
@LoveBodhi , yes: one is main for new Windows, and fallback for Windows XP.

**Comment by Wohlstand** [comment]
As the SMBX2 no longer supports Windows XP (just doesn't launches at all) for a while, this task has no sense.
