### ISSUE TITLE
Make LunaLoader / LunaLoader-exec work on Windows XP

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#28]
We know that current implementation of LunaLoader doesn't works properly under Windows XP and requires us to use a pre-hexed executable (which produces false positives by some dumb anti-viruses).

Here is another DLL injecting example which confirmed as working on all Windows versions include XP:
https://github.com/Hotride/UOFPSPatcher/blob/master/MainScript.cpp#L134
(here also code to attach extra control dialog for manipulating injecting DLL and manipulating with a hacked game)

**Comment by Wohlstand** [comment]
Seems, there is a hexed SMBX.exe won't work on Windows XP because of internal LunaLua changes that breaks the compatibility. Going to close this too. The minimal version of Windows for SMBX2 is Windows 7.

**Comment by LoveBodhi** [comment]
Hexed SMBX.exe works with XP at past. Since SMBX2 MaGLX3, it won't be fully-compatible (some functions are not work) due to something are unsupported (like Shaders), which tested by me before upgrading my PC.

There's a planning for Lua scripting system in TheXTech engine called "XTLua".
