### ISSUE TITLE
NPC.get with section -1 crashes.

### ISSUE THREAD

**Issue by KevinW1998** [WohlSoft/LunaLua#3]
I did some overall testing, it might be affected by some kind of destructor in right after generateFilterTable returns.

Then I tried to change luabind::object theFilter to const luabind::object& theFilter and the result wasn't better: Unhandled luabind::error from nowhere.

**Comment by Wohlstand** [comment]
the better solution is checking INSIDE target function:

``` C++
get(int npcid, int sct)
{
if((sct<0)||(sct>20)) return NULL; // instead of null put dummy object of target type
...
}
```

or

``` C++
get(int npcid, int sct)
{
bool fetchAll=(sct<0);
if(sct<0) sct=0;
else if(sct>20) sct=20;
if(fetchAll)
{
//collect NPC's in all sections
} else
{
//collect NPC's in all sections
}
...
}
```

**Comment by KevinW1998** [comment]
Fixed in https://github.com/Wohlhabend-Networks/LunaDLL/commit/20b4f173ed475a5a2d13589739f93b0499bfa5d3
