### ISSUE TITLE
Dead freeze of the game after loading on Wine

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/LunaLua#48]
A while ago I found the bug that causes the game to deadly freeze after finishing the loading while working on Wine in the Linux environment. At older SMBX2 commit states the game works just fine in the same environment.

The bug was introduced somewhere order than this commit 8f1283430f06760047d5441dae5ffb8c285a9f62. In the older version game works just fine in the same environment. (the SMBX2 commit `e21abba81ede65866e832c67da2c4d6ef6a40164` introduces this bug)

The state of the SMBX2 repository where this bug has been introduced:
![изображение](https://user-images.githubusercontent.com/6751442/213350379-6a08ed5d-c43b-4141-8a4a-7d0115871d87.png)

**Comment by Wohlstand** [comment]
Okay, I there is thing I forgot to note: the ACTUAL LunaLua state https://github.com/WohlSoft/LunaLua/commit/f2e4725d7f04513372da129ac80d14f87a16d226 where it worked just fine. So, go through commits at this state...

**Comment by Wohlstand** [comment]
Okay, I made the fix by myself after some investigation for this issue. Now it's need to test the work on other systems to ensure that nothing got broken.

**Comment by Bluenaxela** [comment]
Seems good on other systems :+1:

**Comment by Wohlstand** [comment]
Thanks for the testing! :+1: 

Note: Remove the "need a test" tag after the thing got been tested and confirmed that it works.
