### ISSUE TITLE
What functions can't I use with the old renderer?

### ISSUE THREAD

**Issue by an-OK-squirrel** [WohlSoft/LunaLua#5]
I'm pretty sure that the cards in MAFAB bosses (on MAGL X2) use ShowImage. I don't have OpenGL, so can I still use those?

**Comment by KevinW1998** [comment]
The current version will check if your computer has OpenGL support and will switch to the default renderer if needed.

**Comment by an-OK-squirrel** [comment]
Yes, but will showImage work, or do nothing?

**Comment by an-OK-squirrel** [comment]
(with the old renderer I mean)

**Comment by KevinW1998** [comment]
you mean loadImage/placeSprite?

**Comment by an-OK-squirrel** [comment]
Yes.

**Comment by KevinW1998** [comment]
Yes, it will work for you for sure!

**Comment by an-OK-squirrel** [comment]
Thanks!

**Comment by an-OK-squirrel** [comment]
Also, is there any docs for onInputUpdate?

**Comment by KevinW1998** [comment]
onInputUpdate is just a event where you can overwrite the player.*KeyPressing fields, i.e.
player.downKeyPressing = false.

If you have any more question I would prefer you ask me at the forums or IRC chat.

**Comment by an-OK-squirrel** [comment]
Yeah, I was going to.

I actually asked these on there earlier :P

**Comment by suicvne** [comment]
```
function onInputUpdate()
  if(player1.altRunKeyPressing) then
    player1.altRunKeyPressing = false; --Simple example for disabling a key
press
  end
end
```

**Comment by an-OK-squirrel** [comment]
Thanks.
