### ISSUE TITLE
Renderer doesn't work on fullscreen in editor-mode.

### ISSUE THREAD

**Issue by KevinW1998** [WohlSoft/LunaLua#7]
Qoute from alejandrogd1:

> On LunaLua when I open it in the editor and bring it to full screen only looks black box, it has no image 

Steps to reproduce:
1.) Start the editor
2.) Open a level / Create a new one
3.) Open level settings and check the checkbox "fullscreen"
4.) Test the level.

**Comment by cramps-man** [comment]
What does he mean by "On LunaLua"?

Also for fullscreen you mean, View->Fullscreen in PGE editor? Because I do not get this issue when testing a level.

**Comment by KevinW1998** [comment]
I am still speaking of the smbx editor, not the PGE editor.

**Comment by Wohlstand** [comment]
cramps-man: LunaLUA is a hacking toolset and extension for the smbx engine which used to do deep research of the SMBX engine and provolide some fixes, improvements and scripting subsystem

**Comment by KevinW1998** [comment]
So SwapBuffers returns ERROR_INVALID_HANDLE when using the fullscreen-mode in the SMBX editor. 
Due to that we have to rewrite the OpenGL module for either support multiple device contextes or cleanup the old one.

**Comment by Bluenaxela** [comment]
I'm already in the middle of refactoring some things for such

**Comment by KevinW1998** [comment]
This is fixed with https://github.com/Wohlhabend-Networks/LunaDLL/commit/e12e5d2eba511a3e4890e29cd1100ad18471789b
